const EXAM_DATE = new Date("2026-11-22T08:00:00-05:00");
const STORAGE_KEY = "unsch-control-room-v2";
const START_DATE = "2026-09-08";

const officialCatalog = {
  "Razonamiento verbal": "etimología,prefijos griegos,sufijos griegos,prefijos latinos y españoles,sinonimia,homonimia,paronimia,polisemia,antonimia,hiperonimia,hiponimia,cohiponimia,términos excluidos,series verbales,analogías,tema,idea principal y secundaria,cohesión,coherencia,referentes,conectores,oraciones incompletas,oración eliminada,plan de redacción,comprensión literal,inferencia,comprensión crítica,inducción,deducción,extrapolación,ironía y doble sentido,subrayado,sumillado,palabra clave,denotación y connotación,paremiología",
  "Lenguaje": "comunicación,signo lingüístico,lenguaje lengua y habla,variación lingüística,castellano peruano,origen del español,fonema y grafía,ortografía de letras,sílaba,diptongo hiato y triptongo,acentuación general,acentuación especial,tilde diacrítica,tilde enfática,compuestos y enclíticos,extranjerismos,morfología,formación de palabras,categorías variables,categorías invariables,frase proposición y oración,sujeto,predicado,concordancia,conectores y deixis,puntuación,signos auxiliares",
  "Literatura": "teoría y géneros,figuras literarias,interpretación literaria,Homero,Dante,Shakespeare,Hugo,Balzac,Kafka,Sartre,Mío Cid,Lazarillo de Tormes,Cervantes,Bécquer,Machado,Lorca,Cela,Isaacs,Darío,Neruda,Rulfo,García Márquez,Borges,Paz,Ollantay,Palma,Matto de Turner,Chocano,Valdelomar,Eguren,Vallejo,Arguedas,Alegría,Ribeyro,Vargas Llosa,Reynoso,Heraud,literatura regional ayacuchana",
  "RLM": "poleas,engranajes,edades,relaciones de parentesco,tiempo,orden,inducción y deducción,planteo de ecuaciones,sucesiones,series,analogías,distribuciones,operadores,operaciones,factorial,combinaciones,variaciones,permutaciones",
  "Aritmética": "lógica,conjuntos,números naturales,numeración,números enteros,divisibilidad,números primos,factorización prima,número de divisores,MCD,algoritmo de Euclides,MCM,números racionales y fracciones,razones,proporciones,magnitudes,reparto proporcional,regla de tres,porcentajes,sucesiones,progresión aritmética y geométrica,sumatorias,media,mediana y moda,probabilidad",
  "Álgebra": "números reales,intervalos,valor absoluto,ecuaciones,inecuaciones,sistemas de ecuaciones,expresiones algebraicas,polinomios,Ruffini,residuo y factor,productos notables,cocientes notables,factorización,relación raíces y coeficientes,funciones,dominio y rango,función lineal,función cuadrática,función raíz,valor absoluto y trozos,operaciones con funciones,función inversa,función exponencial,logaritmos",
  "Geometría": "rectas y ángulos,triángulos,congruencia,polígonos y cuadriláteros,circunferencia,centros notables,proporcionalidad,Teorema de Thales,semejanza,relaciones métricas,áreas,regiones circulares,prismas y pirámides,cilindro cono y esfera,geometría analítica,recta,circunferencia analítica,parábola",
  "Trigonometría": "sistemas angulares,arco y sector,razones trigonométricas,triángulos notables,posición normal,reducción al primer cuadrante,identidades,suma y diferencia,doble mitad y triple,transformaciones,resolución de triángulos,ley de senos,ley de cosenos,ley de tangentes,elevación y depresión,ecuaciones trigonométricas,funciones trigonométricas",
  "Física": "SI dimensiones y vectores,MRU,MRUV,caída libre,proyectiles,MCU y MCUV,leyes de Newton,rozamiento,estática,torque,dinámica,impulso y cantidad de movimiento,trabajo,energía,potencia,fluidos,Coulomb,campo y potencial,condensadores,Ley de Ohm,resistencias,Kirchhoff,electromagnetismo,MAS,ondas y sonido",
  "Química": "materia y cambios,átomo,números cuánticos,configuración electrónica,isótopos y radiactividad,tabla periódica,enlaces,compuestos inorgánicos,reacciones químicas,balanceo,redox,estequiometría,gases,química orgánica,hidrocarburos,ciclos y contaminación,soluciones",
  "Biología": "bioelementos y biomoléculas,célula,nutrición fotosíntesis y energía,relación y coordinación,mitosis y meiosis,reproducción vegetal,reproducción humana,genética,mutaciones cáncer y biotecnología,evolución y biodiversidad,infecciones y parásitos,ecología,impacto ambiental",
  "Anatomía": "sistema digestivo,sistema cardiovascular,sistema respiratorio,sistema urinario,sistema nervioso,sentidos,sistema endocrino,sistema reproductor",
  "Historia Universal": "hominización,civilizaciones antiguas,Grecia,Roma,feudalismo,Renacimiento,Reforma,Revolución francesa,Revolución industrial,guerras mundiales,Guerra Fría,globalización",
  "Historia del Perú": "poblamiento americano,culturas andinas,Tawantinsuyo,conquista,virreinato,rebeliones coloniales,independencia,República Aristocrática,Leguía,militarismo,Velasco y Reforma Agraria,terrorismo,Fujimori,historia reciente,Historia de Ayacucho y Huamanga",
  "Geografía": "relieve,regiones naturales,clima,cuencas e hidrografía,población,actividades económicas,recursos naturales,riesgos,biodiversidad,ambiente",
  "Economía": "escasez y FPP,producción,factores productivos,mercado,oferta y demanda,sistema financiero,inflación,presupuesto,PBI y PBN,comercio exterior,balanza comercial,dinero e interés,política económica,pensamiento económico",
  "Cívica": "persona y familia,parentesco,Constitución,Poder Ejecutivo,Poder Legislativo,Poder Judicial,organismos autónomos,democracia,participación,sistema electoral,derechos humanos,organismos internacionales",
  "Actualidad": "elecciones y organismos electorales,política peruana,Ayacucho y región,geopolítica,economía nacional,ciencia y ambiente,efemérides y cultura"
};

const criticalTopics = new Set("MCD,MCM,conjuntos,divisibilidad,número de divisores,razones,proporciones,porcentajes,edades,sucesiones,operadores,planteo de ecuaciones,ecuaciones,sistemas de ecuaciones,inecuaciones,funciones,triángulos,rectas y ángulos,razones trigonométricas,MRUV,leyes de Newton,trabajo,energía,célula,mitosis y meiosis,genética,estructura atómica,átomo,soluciones,inferencia,comprensión literal,tema,idea principal y secundaria,analogías,signo lingüístico,comunicación,diptongo hiato y triptongo,acentuación general,Historia de Ayacucho y Huamanga,Velasco y Reforma Agraria,oferta y demanda,Estado".split(","));
const highTopics = new Set("estadística,media,mediana y moda,probabilidad,permutaciones,combinaciones,polinomios,áreas,centros notables,identidades,estática,torque,fluidos,enlaces,balanceo,redox,ecología,sistema nervioso,independencia,Tawantinsuyo,mercado,democracia".split(","));

function slug(value) { return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", "\"": "&quot;" })[character]); }
function priorityFor(name) { if (criticalTopics.has(name)) return "S"; if (highTopics.has(name)) return "A"; return "B"; }
function scoreFor(priority) { return priority === "S" ? { h: 5, i: 5, u: 4 } : priority === "A" ? { h: 4, i: 4, u: 3 } : { h: 2, i: 3, u: 2 }; }
function treatmentFor(priority) { return priority === "S" ? "deep" : priority === "A" ? "surface" : "deferred"; }
const catalog = Object.entries(officialCatalog).flatMap(([course, names]) => names.split(",").map((name) => { const priority = priorityFor(name); const s = scoreFor(priority); return { id: `${slug(course)}-${slug(name)}`, course, name, priority, treatment: treatmentFor(priority), ...s, p0: s.h * s.i * s.u }; }));

function loadState() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || { startDate: START_DATE, area: "science", attempts: [], recommendationsAccepted: [] }; } catch { return { startDate: START_DATE, area: "science", attempts: [], recommendationsAccepted: [] }; } }
let state = loadState();
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function dateAtMidnight(value) { return new Date(`${value}T00:00:00`); }
function phaseInfo() { const day = Math.max(1, Math.floor((Date.now() - dateAtMidnight(state.startDate)) / 86400000) + 1); if (day <= 20) return { id: "build", day, total: 20, title: `Fase 1 · Construir`, objective: "Construir el MVP cognitivo: llevar microtemas S/A hacia K3, sin perseguir perfección.", formula: "P0 = H × I × U" }; if (day <= 30) return { id: "break", day: day - 20, total: 10, title: "Fase 2 · Romper", objective: "Forzar fallos con preguntas nuevas, mezcladas y cronometradas. Cada fallo debe dejar una corrección.", formula: "R = F × I × D" }; if (day <= 50) return { id: "repair", day: day - 30, total: 20, title: "Fase 3 · Reparar", objective: "Reducir los riesgos altos con una intervención definida por el tipo de fallo.", formula: "R = F × I × D" }; return { id: "final", day: day - 50, total: Math.max(1, Math.ceil((EXAM_DATE - Date.now()) / 86400000)), title: "Tramo final · Verificar", objective: "Simulacros, reparación de riesgos críticos y recuperación. No abrir frentes de bajo retorno.", formula: "R + simulacros" }; }
function topicAttempts(id) { return state.attempts.filter((attempt) => attempt.topicId === id); }
function median(values) { if (!values.length) return null; const list = [...values].sort((a, b) => a - b); const mid = Math.floor(list.length / 2); return list.length % 2 ? list[mid] : Math.round((list[mid - 1] + list[mid]) / 2); }
function courseImpact(course) { const science = ["RLM", "Aritmética", "Álgebra", "Geometría", "Trigonometría", "Física", "Química", "Biología", "Anatomía"]; const high = state.area === "science" ? science : ["Razonamiento verbal", "Lenguaje", "Literatura", "Historia Universal", "Historia del Perú", "Geografía", "Economía", "Cívica"]; return high.includes(course) ? 5 : 3; }
function metrics(topic) { const attempts = topicAttempts(topic.id); const fresh = attempts.filter((a) => a.isNew); const retention = attempts.filter((a) => a.review === "72"); const errors = attempts.filter((a) => !a.correct); const recurring = errors.filter((error) => errors.filter((other) => other.errorType === error.errorType).length > 1); const freshRate = fresh.length ? fresh.filter((a) => a.correct).length / fresh.length : null; const retentionRate = retention.length ? retention.filter((a) => a.correct).length / retention.length : null; const time = median(attempts.map((a) => a.seconds)); let k = "K0"; if (attempts.length >= 1) k = "K1"; if (attempts.length >= 2) k = "K2"; if (fresh.length >= 2 && freshRate >= .7) k = "K3"; if (fresh.length >= 4 && freshRate >= .8) k = "K4"; if (k === "K4" && retentionRate !== null && retentionRate >= .85 && time !== null && time <= 90 && !recurring.length) k = "K5"; const errorRate = attempts.length ? errors.length / attempts.length : 0; const recurrence = errors.length ? recurring.length / errors.length : 0; const timePenalty = time ? Math.min(1, Math.max(0, (time - 90) / 120)) : 0; const deficit = (5 - Number(k.slice(1))) / 5; const weakness = Math.max(1, Math.min(5, 1 + 4 * (.4 * errorRate + .25 * recurrence + .2 * timePenalty + .15 * deficit))); const risk = Math.round(topic.h * courseImpact(topic.course) * weakness); return { attempts, fresh, errors, recurring, freshRate, retentionRate, time, k, weakness, risk }; }
function percent(value) { return value === null ? "—" : `${Math.round(value * 100)}%`; }
function formatTime(seconds) { if (seconds === null) return "—"; return seconds >= 60 ? `${Math.floor(seconds / 60)}m ${seconds % 60}s` : `${seconds}s`; }
function treatmentLabel(treatment) { return treatment === "deep" ? "PROFUNDO" : treatment === "surface" ? "SUPERFICIAL" : "DIFERIDO"; }

function renderCountdown() { const diff = Math.max(0, EXAM_DATE - Date.now()); const days = Math.floor(diff / 86400000); const hours = Math.floor((diff % 86400000) / 3600000); const minutes = Math.floor((diff % 3600000) / 60000); document.querySelector("#countdown-days").textContent = days; document.querySelector("#countdown-full").textContent = `${days}d ${String(hours).padStart(2, "0")}h ${String(minutes).padStart(2, "0")}m`; }
function renderMission() { const phase = phaseInfo(); document.querySelector("#phase-title").textContent = `${phase.title} · Día ${phase.day}/${phase.total}`; document.querySelector("#phase-objective").textContent = phase.objective; document.querySelector("#decision-formula").textContent = phase.formula; document.querySelectorAll(".phase-progress span").forEach((item) => item.classList.toggle("active", item.id.startsWith(phase.id))); }
function renderMetrics() { const all = catalog.map((topic) => ({ topic, m: metrics(topic) })); const weightedTotal = all.reduce((sum, item) => sum + item.topic.p0 * 5, 0); const weightedProgress = all.reduce((sum, item) => sum + item.topic.p0 * Number(item.m.k.slice(1)), 0); const priority = all.filter((item) => item.topic.priority === "S" || item.topic.priority === "A"); const k3 = priority.filter((item) => Number(item.m.k.slice(1)) >= 3).length; const attempts = state.attempts; const fresh = attempts.filter((a) => a.isNew); const retention = attempts.filter((a) => a.review === "72"); const errors = attempts.filter((a) => !a.correct); const recurring = errors.filter((error) => errors.filter((other) => other.topicId === error.topicId && other.errorType === error.errorType).length > 1); document.querySelector("#metric-coverage").textContent = `${Math.round(weightedProgress / weightedTotal * 100)}%`; document.querySelector("#metric-k3").textContent = `${k3} / ${priority.length}`; document.querySelector("#metric-fresh").textContent = fresh.length ? percent(fresh.filter((a) => a.correct).length / fresh.length) : "—"; document.querySelector("#metric-retention").textContent = retention.length ? percent(retention.filter((a) => a.correct).length / retention.length) : "—"; document.querySelector("#metric-time").textContent = formatTime(median(attempts.map((a) => a.seconds))); document.querySelector("#metric-repeated").textContent = recurring.length; const counts = { deep: 0, surface: 0, deferred: 0 }; catalog.forEach((topic) => counts[topic.treatment]++); document.querySelector("#catalog-summary").textContent = `${catalog.length} microtemas oficiales cargados. ${counts.deep} profundos, ${counts.surface} superficiales y ${counts.deferred} diferidos por estrategia inicial.`; document.querySelector("#strategy-numbers").innerHTML = `<span><b>${counts.deep}</b>profundos</span><span><b>${counts.surface}</b>superficiales</span><span><b>${counts.deferred}</b>diferidos</span>`; }
function recommendedTopics() { const phase = phaseInfo(); const enriched = catalog.map((topic) => ({ topic, m: metrics(topic) })); if (phase.id === "build") return enriched.filter((item) => item.topic.treatment !== "deferred" && Number(item.m.k.slice(1)) < 3).sort((a, b) => b.topic.p0 - a.topic.p0 || a.m.attempts.length - b.m.attempts.length).slice(0, 4); return enriched.filter((item) => item.m.attempts.length || item.topic.treatment === "deep").sort((a, b) => b.m.risk - a.m.risk).slice(0, 4); }
function renderDecision() { const phase = phaseInfo(); const action = recommendedTopics(); const explanation = phase.id === "build" ? "Primero se trabajan los microtemas recurrentes, de alto impacto y que desbloquean otros. No se premia lo cómodo." : phase.id === "break" ? "La práctica se usa para revelar el límite del sistema. Prioridad: alto riesgo, preguntas nuevas y tiempo medido." : "Se repara el riesgo, no el tema que simplemente se siente difícil."; document.querySelector("#decision-explanation").textContent = explanation; document.querySelector("#action-list").innerHTML = action.map(({ topic, m }, index) => `<li><span class="rank">0${index + 1}</span><div><b>${topic.course} · ${topic.name}</b><small>${phase.id === "build" ? `P0 ${topic.p0} · ${treatmentLabel(topic.treatment)}` : `R ${m.risk} · D ${m.weakness.toFixed(1)}/5`}</small></div><span class="goal">${m.k} → ${Number(m.k.slice(1)) < 3 ? "K3" : "verificar"}</span></li>`).join(""); const errors = state.attempts.filter((a) => !a.correct); const recurrentGroups = Object.values(errors.reduce((groups, item) => { const key = `${item.topicId}|${item.errorType}`; groups[key] = groups[key] || []; groups[key].push(item); return groups; }, {})).filter((group) => group.length >= 2).sort((a, b) => b.length - a.length); const alert = document.querySelector("#recurrent-alert"); if (!errors.length) alert.innerHTML = "<strong>Sin fallos registrados aún.</strong><span>Registra el primero: el sistema necesita evidencia.</span>"; else if (recurrentGroups.length) { const group = recurrentGroups[0]; const topic = catalog.find((item) => item.id === group[0].topicId); alert.innerHTML = `<strong>Fallo reincidente ×${group.length}: ${topic.name}</strong><span>${errorLabel(group[0].errorType)}. Próxima intervención: ${intervention(group.length, group[0].errorType)}.</span>`; } else alert.innerHTML = `<strong>${errors.length} fallos registrados y clasificados.</strong><span>Aún no hay patrón reincidente. Sigue probando con preguntas nuevas.</span>`; }
let activeTreatment = "all"; let activeCourse = "all"; let activeK = "all";
function renderTopics() { const rows = catalog.map((topic) => ({ topic, m: metrics(topic) })).filter(({ topic, m }) => (activeTreatment === "all" || topic.treatment === activeTreatment || (activeTreatment === "risk" && m.risk >= 60 && m.attempts.length)) && (activeCourse === "all" || topic.course === activeCourse) && (activeK === "all" || m.k === activeK)); document.querySelector("#topics-body").innerHTML = rows.map(({ topic, m }) => `<tr><td><b>${topic.name}</b><small>${topic.course}</small></td><td><span class="treatment ${topic.treatment}">${treatmentLabel(topic.treatment)}</span></td><td>${topic.p0}</td><td>${m.k}</td><td>${percent(m.freshRate)}</td><td>${percent(m.retentionRate)}</td><td>${formatTime(m.time)}</td><td>${m.errors.length}</td><td class="${m.risk >= 60 && m.attempts.length ? "risk-high" : m.risk >= 35 && m.attempts.length ? "risk-medium" : ""}">${m.attempts.length ? m.risk : "—"}</td></tr>`).join("") || '<tr><td colspan="9">No hay microtemas que coincidan con los filtros.</td></tr>'; }
function renderLedger() { const errors = state.attempts.filter((attempt) => !attempt.correct).slice(-6).reverse(); document.querySelector("#ledger-list").innerHTML = errors.length ? errors.map((error) => { const topic = catalog.find((item) => item.id === error.topicId); return `<article class="ledger-entry"><div><b>${topic.course} · ${topic.name}</b><small>${escapeHtml(error.source)}</small></div><div class="ledger-failure"><b>${errorLabel(error.errorType)}</b><small>${formatTime(error.seconds)} · ${error.isNew ? "Nueva" : "Repetida"}</small></div><div class="ledger-correction">“${escapeHtml(error.correction)}”</div><time>${new Date(error.date).toLocaleDateString("es-PE", { day: "2-digit", month: "short" })}</time></article>`; }).join("") : '<p class="empty-ledger">Todavía no hay fallos guardados. El primer registro debe incluir el patrón que no viste y una corrección mínima verificable.</p>'; }
function errorLabel(type) { return ({ recognition: "No reconocí el modelo", concept: "Olvidé concepto", "wrong-model": "Modelo equivocado", procedure: "Procedimiento", calculation: "Cálculo", reading: "Lectura", time: "Tiempo", distractor: "Distractor" })[type] || "Fallo"; }
function intervention(count, type) { if (count >= 4) return "marcar riesgo y hacer simulación mezclada"; if (count === 3) return "5 variantes mezcladas"; if (count === 2) return type === "wrong-model" || type === "recognition" ? "discriminación entre modelos" : "variante con corrección inmediata"; return "explicación y una variante"; }
function renderRecommendations() { const phase = phaseInfo(); const candidates = catalog.map((topic) => ({ topic, m: metrics(topic) })).filter((item) => item.m.attempts.length).sort((a, b) => b.m.risk - a.m.risk).slice(0, 5); const empty = '<p class="dialog-copy">Aún no hay suficientes intentos. Registra preguntas nuevas y fallos para producir recomendaciones.</p>'; document.querySelector("#recommendation-list").innerHTML = candidates.length ? candidates.map(({ topic, m }) => { const high = m.risk >= 60; return `<div class="recommendation ${high ? "" : "good"}"><span class="arrow">${high ? "↑" : "→"}</span><div><b>${topic.name} · R ${m.risk} · D ${m.weakness.toFixed(1)}/5</b><p>${high ? `Proponer ${topic.treatment === "deferred" ? "subir a SUPERFICIAL" : "intervención inmediata"}: ${m.errors.length} fallos, ${formatTime(m.time)} de mediana.` : "Mantener estrategia actual; aún no justifica más tiempo que los riesgos altos."}</p></div></div>`; }).join("") : empty; }
function fillTopicSelects() { const options = catalog.map((topic) => `<option value="${topic.id}">${topic.course} · ${topic.name}</option>`).join(""); document.querySelector("#attempt-topic").innerHTML = options; document.querySelector("#course-filter").insertAdjacentHTML("beforeend", [...new Set(catalog.map((topic) => topic.course))].map((course) => `<option value="${course}">${course}</option>`).join("")); }
function renderAll() { renderCountdown(); renderMission(); renderMetrics(); renderDecision(); renderTopics(); renderLedger(); renderRecommendations(); }

document.querySelectorAll("[data-close]").forEach((button) => button.addEventListener("click", () => document.querySelector(`#${button.dataset.close}`).close()));
document.querySelector("#attempt-button").addEventListener("click", () => document.querySelector("#attempt-dialog").showModal());
document.querySelector("#error-button").addEventListener("click", () => { document.querySelector("#attempt-result").value = "false"; document.querySelector("#attempt-dialog").showModal(); document.querySelector("#attempt-topic").focus(); });
document.querySelector("#attempt-result").addEventListener("change", (event) => { document.querySelector("#failure-fields").hidden = event.target.value === "true"; });
document.querySelector("#attempt-form").addEventListener("submit", (event) => { event.preventDefault(); const correct = document.querySelector("#attempt-result").value === "true"; if (!correct && !document.querySelector("#error-correction").value.trim()) { document.querySelector("#error-correction").setCustomValidity("Registra una corrección mínima para que el fallo sea reparable."); document.querySelector("#error-correction").reportValidity(); return; } const attempt = { id: crypto.randomUUID(), topicId: document.querySelector("#attempt-topic").value, source: document.querySelector("#attempt-source").value.trim(), correct, seconds: Number(document.querySelector("#attempt-time").value), isNew: document.querySelector("#attempt-new").value === "true", review: document.querySelector("#attempt-review").value, errorType: correct ? null : document.querySelector("#error-type").value, correction: correct ? null : document.querySelector("#error-correction").value.trim(), date: new Date().toISOString() }; state.attempts.push(attempt); saveState(); event.target.reset(); document.querySelector("#failure-fields").hidden = false; document.querySelector("#attempt-dialog").close(); renderAll(); });
document.querySelector("#error-correction").addEventListener("input", (event) => event.target.setCustomValidity(""));
document.querySelectorAll(".filter").forEach((button) => button.addEventListener("click", () => { document.querySelector(".filter.active").classList.remove("active"); button.classList.add("active"); activeTreatment = button.dataset.treatment; renderTopics(); }));
document.querySelector("#course-filter").addEventListener("change", (event) => { activeCourse = event.target.value; renderTopics(); }); document.querySelector("#k-filter").addEventListener("change", (event) => { activeK = event.target.value; renderTopics(); });
document.querySelector("#area").value = state.area; document.querySelector("#area").addEventListener("change", (event) => { state.area = event.target.value; saveState(); renderAll(); });
document.querySelectorAll("#strategy-button,#review-button,#view-strategy").forEach((button) => button.addEventListener("click", () => document.querySelector("#strategy-dialog").showModal()));
document.querySelector("#accept-recommendations").addEventListener("click", () => document.querySelector("#strategy-dialog").close());
document.querySelector("#plan-button").addEventListener("click", () => { document.querySelector("#campaign-start").value = state.startDate; document.querySelector("#plan-dialog").showModal(); });
document.querySelector("#plan-form").addEventListener("submit", (event) => { event.preventDefault(); state.startDate = document.querySelector("#campaign-start").value; saveState(); document.querySelector("#plan-dialog").close(); renderAll(); });
document.querySelector("#show-k-rules").addEventListener("click", () => document.querySelector("#k-dialog").showModal());
fillTopicSelects(); renderAll(); setInterval(renderCountdown, 30000);
